name: Crossfit Power Company
shortname: CFPP
markdown: redcarpet
pygments: true
timezone: America/San_Francisco
url: //jpatzer.github.io/crossfitpowercompany
assets: /crossfitpowercompany/assets
imageasset: /crossfitpowercompany/assets/images
paginate: 2
paginate_path: "blog/page:num"
